// Mainteno Next — core state, API, authentication and data loading.
const SB='https://vlxpqsmmzhnhkceqcnes.supabase.co',KEY='sb_publishable_DMRcgCwwv0R4XHYU1TZxLQ_dbEfDgBf',A=document.getElementById('app'),T=document.getElementById('toast'),SYNC=document.getElementById('syncbar');let installPrompt=null;addEventListener('beforeinstallprompt',ev=>{ev.preventDefault();installPrompt=ev;if(S.u&&S.page==='profile')render()});
let S={s:null,u:null,p:null,page:'dashboard',selected:null,assets:[],wo:[],parts:[],woParts:[],atts:[],procedures:[],steps:[],runs:[],results:[],notifications:[],drafts:[],pm:[],meters:[],pos:[],polines:[],audit:[],profiles:[],machineKpis:[],techKpis:[],kpi:null,health:null,requests:[],vendors:[],locations:[],teams:[],teamMembers:[],portals:[],exceptions:[],templates:[],newWoAsset:null,publicToken:null,publicPortal:null,pendingAsset:null,editStepId:null};
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m,er=0){T.textContent=m;T.className='toast'+(er?' err':'');T.hidden=false;setTimeout(()=>T.hidden=true,2500)}
function showInviteCode(code,expiresAt){let wrap=document.createElement('div');wrap.className='scanWrap';wrap.innerHTML=`<div class="scanBox"><h3>Invitation technicien</h3><p class="mut">Ce code est à usage unique et expire le ${e(new Date(expiresAt).toLocaleString('fr-FR'))}.</p><div class="card" style="font-family:monospace;font-size:20px;text-align:center;word-break:break-all"><b>${e(code)}</b></div><div class="stack"><button class="btn primary" id="inviteCopy">Copier le code</button><button class="btn" id="inviteClose">Fermer</button></div></div>`;document.body.appendChild(wrap);wrap.querySelector('#inviteCopy').onclick=async()=>{await navigator.clipboard.writeText(code);toast('Code copié')};wrap.querySelector('#inviteClose').onclick=()=>wrap.remove()}
function save(s){S.s=s;s?localStorage.setItem('mainteno_next_session',JSON.stringify(s)):localStorage.removeItem('mainteno_next_session')}
async function rf(){let r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:S.s.refresh_token})}),j=await r.json();if(!r.ok)throw Error('Session expirée');save(j)}
async function api(p,o={},retry=1){let h={...(o.headers||{}),apikey:KEY};if(S.s?.access_token)h.Authorization='Bearer '+S.s.access_token;if(p.startsWith('/rest/'))h['Content-Type']=h['Content-Type']||'application/json';let r=await fetch(SB+p,{...o,headers:h});if(r.status===401&&retry&&S.s?.refresh_token){await rf();return api(p,o,0)}let tx=await r.text(),j=tx?(()=>{try{return JSON.parse(tx)}catch{return tx}})():null;if(!r.ok)throw Error(j?.message||j?.msg||j?.error_description||'Erreur '+r.status);return j}
const sel=(t,q='select=*')=>api('/rest/v1/'+t+'?'+q),ins=(t,d)=>api('/rest/v1/'+t,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(d)}),upd=(t,id,d)=>api('/rest/v1/'+t+'?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(d)}),rpc=(n,d={})=>api('/rest/v1/rpc/'+n,{method:'POST',body:JSON.stringify(d)});
function isMgr(){return ['admin','manager','supervisor'].includes(S.p?.role)}function isTech(){return ['technician','supervisor'].includes(S.p?.role)}
async function login(email,password){let r=await fetch(SB+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg);save(j);S.u=j.user;await loadAll()}
async function inviteValid(code){let r=await fetch(SB+'/rest/v1/rpc/nx_signup_invite_valid',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({p_code:(code||'').trim()})}),j=await r.json();return r.ok&&j===true}
async function signup(name,email,password,inviteCode){if(!await inviteValid(inviteCode))throw Error("Code d'invitation invalide ou expiré");let r=await fetch(SB+'/auth/v1/signup',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{full_name:name,invite_code:(inviteCode||'').trim()}})}),j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||j.message||'Création impossible');if(j.access_token){save(j);S.u=j.user;await loadAll();return true}return false}
async function loadAll(){let p=await sel('profiles','select=*&id=eq.'+S.u.id);S.p=p[0];let [assets,wo,parts,woParts,atts,procedures,steps,runs,results,notifications,drafts,pm,meters,pos,polines,audit,profiles,requests,vendors,locations,teams,teamMembers,portals,exceptions,templates]=await Promise.all([sel('nx_assets','select=*&order=code.asc'),sel('nx_work_orders','select=*&order=requested_at.desc'),sel('nx_parts','select=*&order=name.asc'),sel('nx_work_order_parts','select=*'),sel('nx_attachments','select=*&order=created_at.asc'),sel('nx_procedures','select=*'),sel('nx_procedure_steps','select=*&order=position.asc'),sel('nx_work_order_procedures','select=*'),sel('nx_step_results','select=*'),sel('nx_notifications','select=*&order=created_at.desc&limit=100'),sel('nx_work_order_drafts','select=*&user_id=eq.'+S.u.id),sel('nx_pm_plans','select=*&order=next_due_at.asc.nullslast'),sel('nx_meters','select=*&order=name.asc'),sel('nx_purchase_orders','select=*&order=created_at.desc'),sel('nx_purchase_order_lines','select=*'),sel('nx_audit_log','select=*&order=created_at.desc&limit=100'),sel('profiles','select=*&active=eq.true&order=full_name.asc'),sel('nx_work_requests','select=*&order=created_at.desc'),sel('nx_vendors','select=*&active=eq.true&order=name.asc'),rpc('nx_location_tree',{}),sel('nx_teams','select=*&active=eq.true&order=name.asc'),sel('nx_team_members','select=*'),sel('nx_request_portals','select=*&order=created_at.desc'),sel('nx_procedure_exceptions','select=*&order=created_at.desc'),sel('nx_work_order_templates','select=*&active=eq.true&order=name.asc')]);Object.assign(S,{assets,wo,parts,woParts,atts,procedures,steps,runs,results,notifications,drafts,pm,meters,pos,polines,audit,profiles,requests,vendors,locations,teams,teamMembers,portals,exceptions,templates});if(isMgr()){[S.kpi,S.machineKpis,S.techKpis,S.health]=await Promise.all([rpc('nx_dashboard_kpis',{}),rpc('nx_machine_kpis',{}),rpc('nx_technician_kpis',{}),rpc('nx_system_health',{})])}cacheSnapshot()}
function cacheSnapshot(){try{localStorage.setItem('mainteno_snapshot',JSON.stringify({p:S.p,assets:S.assets,wo:S.wo,parts:S.parts,woParts:S.woParts,atts:S.atts,procedures:S.procedures,steps:S.steps,runs:S.runs,results:S.results,drafts:S.drafts,pm:S.pm,meters:S.meters,pos:S.pos,polines:S.polines,notifications:S.notifications,requests:S.requests,vendors:S.vendors,locations:S.locations,teams:S.teams,teamMembers:S.teamMembers,portals:S.portals,exceptions:S.exceptions,templates:S.templates,profiles:S.profiles,kpi:S.kpi,machineKpis:S.machineKpis,techKpis:S.techKpis,health:S.health,ts:Date.now()}))}catch{}}
function restoreSnapshot(){try{let x=JSON.parse(localStorage.getItem('mainteno_snapshot')||'null');if(x)Object.assign(S,x)}catch{}}

function nval(v){return v===''||v==null?null:Number(v)}
function activeLocations(){return S.locations.filter(l=>l.active!==false)}
function activeTechs(){return S.profiles.filter(p=>p.active!==false&&['technician','supervisor','manager','admin'].includes(p.role))}
