// Mainteno Next — CSV/PDF exports and reporting helpers.
function csvCell(v){if(v==null)return '';let x=String(v).replace(/\r?\n/g,' ');return '"'+x.replace(/"/g,'""')+'"'}
function downloadCsv(name,rows){if(!rows?.length){toast('Aucune donnée à exporter',1);return}let cols=Object.keys(rows[0]),text='\ufeff'+cols.map(csvCell).join(';')+'\r\n'+rows.map(r=>cols.map(c=>csvCell(r[c])).join(';')).join('\r\n');let b=new Blob([text],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function printReport(title,rows){if(!rows?.length){toast('Aucune donnée pour le rapport',1);return}let cols=Object.keys(rows[0]),html=`<!doctype html><html><head><meta charset="utf-8"><title>${e(title)}</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}h1{font-size:22px}.meta{color:#666;font-size:12px;margin-bottom:16px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #ccc;padding:5px;text-align:left;vertical-align:top}th{background:#eee}@page{size:A4 landscape;margin:10mm}</style></head><body><h1>${e(title)}</h1><div class="meta">Généré par Mainteno Next · ${new Date().toLocaleString('fr-FR')}</div><table><thead><tr>${cols.map(c=>`<th>${e(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${e(r[c]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table><script>onload=()=>setTimeout(()=>print(),250)<\/script></body></html>`;let w=open('','_blank');if(!w){toast('Autorise les fenêtres pop-up pour le PDF',1);return}w.document.write(html);w.document.close()}
async function exportWorkOrders(asPdf=false){let rows=await rpc('nx_export_work_orders',{p_from:new Date(Date.now()-30*86400000).toISOString(),p_to:new Date(Date.now()+86400000).toISOString()});asPdf?printReport('Rapport OT - 30 derniers jours',rows):downloadCsv('mainteno_ot_30j.csv',rows)}
async function exportStock(asPdf=false){let rows=await rpc('nx_export_stock',{});asPdf?printReport('Rapport stock et pièces',rows):downloadCsv('mainteno_stock.csv',rows)}
async function exportMachineKpis(asPdf=false){let rows=await rpc('nx_machine_kpis',{p_from:new Date(Date.now()-30*86400000).toISOString(),p_to:new Date().toISOString()});asPdf?printReport('KPI Machines - 30 jours',rows):downloadCsv('mainteno_kpi_machines_30j.csv',rows)}
async function exportTechKpis(asPdf=false){let rows=await rpc('nx_technician_kpis',{p_from:new Date(Date.now()-30*86400000).toISOString(),p_to:new Date().toISOString()});asPdf?printReport('KPI Équipe - 30 jours',rows):downloadCsv('mainteno_kpi_equipe_30j.csv',rows)}
async function exportAssetHistory(assetId,asPdf=false){let a=S.assets.find(x=>x.id===assetId),rows=await rpc('nx_export_asset_history',{p_asset_id:assetId,p_from:new Date(Date.now()-365*86400000).toISOString(),p_to:new Date(Date.now()+86400000).toISOString()});let code=(a?.code||'machine').replace(/[^a-zA-Z0-9_-]/g,'_');asPdf?printReport('Historique machine '+(a?.code||''),rows):downloadCsv('mainteno_historique_'+code+'.csv',rows)}
