// Mainteno Next — navigation, shell, common UI helpers and router.
function applyPendingAssetRoute(){if(S.pendingAsset&&S.assets.some(a=>a.id===S.pendingAsset)){S.selected=S.pendingAsset;S.page='assetDetail';S.pendingAsset=null;return true}return false}
function managerNav(){let unread=S.notifications.filter(n=>!n.read_at).length;return[['dashboard','Dashboard','▦'],['assets','Parc','⚙'],['workorders','OT','☰'],['requests','Demandes','!'],['planning','Planning','▤'],['pm','Préventif','↻'],['meters','Compteurs','◴'],['inventory','Stock','▣'],['purchase','Achats','🛒'],['kpis','KPI','▥'],['reliability','Fiabilité','⌁'],['notifications','Alertes '+(unread?'('+unread+')':''),'🔔'],['audit','Audit','⌁'],['templates','Modèles OT','▧'],['procedures','Procédures','☑'],['organization','Organisation','🏭'],['diagnostic','Diagnostic','✓']]}
function nav(){if(isMgr())return managerNav();let unread=S.notifications.filter(n=>!n.read_at).length;return[['techhome','Accueil','▦'],['workorders','Mes OT','☰'],['requests','Demandes','!'],['scan','Scanner','⌗'],['assets','Machines','⚙'],['notifications','Alertes '+(unread?'('+unread+')':''),'🔔'],['profile','Profil','👤']]}
function mobileNav(){let unread=S.notifications.filter(n=>!n.read_at).length;if(!isMgr())return[['techhome','Accueil','▦'],['workorders','Mes OT','☰'],['scan','Scanner','⌗'],['notifications','Alertes'+(unread?' '+unread:''),'🔔'],['profile','Profil','👤']];return[['dashboard','Accueil','▦'],['assets','Parc','⚙'],['workorders','OT','☰'],['notifications','Alertes'+(unread?' '+unread:''),'🔔'],['more','Plus','•••']]}
function shell(c){let n=nav(),m=mobileNav();A.innerHTML=`<header class="top"><div class="brand">Mainteno Next<small>${e(S.p?.full_name||'')} · <span class="statusDot ${navigator.onLine?'':'off'}"></span>${navigator.onLine?'En ligne':'Hors ligne'}</small></div><button class="btn" data-a="logout">Quitter</button></header><div class="layout"><aside class="side">${n.map(x=>`<button data-p="${x[0]}" class="${S.page===x[0]?'on':''}">${x[2]} &nbsp;${x[1]}</button>`).join('')}</aside><main class="content">${c}</main></div><nav class="mobileNav">${m.map(x=>`<button data-p="${x[0]}" class="${S.page===x[0]?'on':''}">${x[2]}<br>${x[1]}</button>`).join('')}</nav>`}
function publicRequestView(){let p=S.publicPortal;if(!p){A.innerHTML=`<div class="login"><div class="card"><h2>Lien invalide ou désactivé</h2><p class="mut">Contacte le service maintenance.</p></div></div>`;return}A.innerHTML=`<div class="login"><div class="card"><h1>Demande maintenance</h1><p class="sub">${e(p.name)}</p>${p.asset_name?`<div class="notice" style="margin:12px 0"><b>${e(p.asset_code||'')} · ${e(p.asset_name)}</b>${p.location_name?`<div>${e(p.location_name)}</div>`:''}</div>`:''}<form id="publicRequest"><div class="field"><label>Problème *</label><input name="title" maxlength="160" required placeholder="Ex: fuite d'eau machine 4"></div><div class="field"><label>Description</label><textarea name="description" maxlength="4000" placeholder="Décris le problème observé"></textarea></div><div class="field"><label>Priorité</label><select name="priority"><option value="${e(p.default_priority)}">${e(p.default_priority)} (par défaut)</option><option value="low">low</option><option value="medium">medium</option><option value="high">high</option><option value="urgent">urgent</option></select></div><button class="btn primary" style="width:100%">Envoyer la demande</button></form></div></div>`}
function loginView(sign=false){A.innerHTML=`<div class="login"><div class="card"><h1>Mainteno Next</h1>${sign?`<form id="signup"><div class="field"><label>Nom complet</label><input name="name" autocomplete="name" required></div><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Code d'invitation</label><input name="invite_code" autocomplete="off" required placeholder="MN-…"><div class="mut">Demande ce code à ton responsable.</div></div><div class="field"><label>Mot de passe</label><input name="pass" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label>Confirmer le mot de passe</label><input name="confirm" type="password" minlength="8" autocomplete="new-password" required></div><button class="btn primary" style="width:100%">Créer mon compte</button></form><button class="btn" style="width:100%;margin-top:10px" onclick="loginView(false)">J'ai déjà un compte</button>`:`<form id="login"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Mot de passe</label><input name="pass" type="password" autocomplete="current-password" required></div><button class="btn primary" style="width:100%">Connexion</button></form><button class="btn" style="width:100%;margin-top:10px" onclick="loginView(true)">Créer un compte</button>`}</div></div>`}
function pill(v){let c=['online','completed','validated','approved','complete'].includes(v)?'green':['offline','urgent','rejected'].includes(v)?'red':['on_hold','limited','partially_fulfilled'].includes(v)?'orange':'blue';return `<span class="pill ${c}">${e(v||'—')}</span>`}
function metric(l,v){return `<div class="metric"><span>${e(l)}</span><b>${e(v)}</b></div>`}
function woRow(w){let a=S.assets.find(x=>x.id===w.asset_id);return `<div class="listitem" data-wo="${w.id}"><div class="row"><div><b>#${w.wo_number} · ${e(w.title)}</b><div class="mut">${e(a?.code||'')} · ${e(w.type)}</div></div>${pill(w.status)}</div></div>`}

function loadReliability(){
  if(typeof window.reliability==='function')return window.reliability();
  let old=document.getElementById('maintenoReliabilityModule');
  if(old){toast('Chargement du module Fiabilité…');return}
  let s=document.createElement('script');s.id='maintenoReliabilityModule';s.src='/js/reliability.js?v=20260914p13';
  s.onload=()=>{if(typeof window.reliability==='function')window.reliability();else toast('Module Fiabilité indisponible',1)};
  s.onerror=()=>{s.remove();toast('Impossible de charger Fiabilité. Vérifie la connexion.',1)};
  document.body.appendChild(s);
}

function render(){if(S.publicToken)return publicRequestView();if(!S.u)return loginView();let f={dashboard,techhome:techHome,assets,assetDetail,assetQr,assetForm,workorders,newwo,templates,procedures,procedureDetail,woDetail,requests,requestForm,requestConvert,purchase,purchaseDetail,poForm,vendors,planning,pm,pmForm,meters,meterForm,inventory,partForm,kpis,reliability:loadReliability,notifications,audit,profile,organization,diagnostic,syncconflicts,more,scan:()=>startScanner()};return (f[S.page]||(isMgr()?dashboard:techHome))()}
